repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-symlinks
      #- id: check-yaml
      - id: detect-private-key
  - repo: https://github.com/hadolint/hadolint
    rev: "v2.12.0"
    hooks:
      - id: hadolint-docker
        args:
          - --ignore
          - DL4006
          - --ignore
          - DL3015
          - --ignore
          - DL4006   # Use absolute WORKDIR
          - --ignore
          - DL3015   # Use ADD instead of COPY
          - --ignore
          - DL3018   # Pin versions in apk add
          - --ignore
          - DL4001   # Either use Wget or Curl but not both
          - --ignore
          - DL3042   # Avoid pip cache dir
          - --ignore
          - DL3013   # Pin versions in pip
          - --ignore
          - DL3002   # Last USER should not be root
  - repo: https://github.com/sirosen/check-jsonschema
    rev: 0.30.0
    hooks:
      - id: check-github-workflows

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        name: Detect secrets
        description: Detects high entropy strings that are likely to be passwords.
        entry: detect-secrets-hook
        language: python
        # for backward compatibility
        files: .*  # all files
