apiVersion: v1
data:
  AUTOINSTALL_COMPONENTS: "{{ .Values.autoInstallComponents }}"
  DEFAULT_TARGET_NAMESPACE: {{ .Values.defaultNamespace }}
kind: ConfigMap
metadata:
  labels:
    operator.tekton.dev/release: v0.77.0
  name: tekton-config-defaults
  namespace: tekton-operator
