apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/instance: default
  name: tekton-operator-info
  namespace: tekton-operator
rules:
  - apiGroups:
      - ""
    resourceNames:
      - tekton-operator-info
    resources:
      - configmaps
    verbs:
      - get
      - describe
