apiVersion: v1
kind: Service
metadata:
  labels:
    app: tekton-pipelines-controller
    version: v0.76.0
  name: tekton-operator

spec:
  ports:
    - name: http-metrics
      port: 9090
      protocol: TCP
      targetPort: 9090
  selector:
    app: tekton-operator
    name: tekton-operator
