---
apiVersion: tekton.dev/v1
kind: TaskRun
metadata:
  name: execute-tofu-run
  namespace: tekton-ci
spec:
  taskRef:
    name: execute-tofu
  params:
    - name: ACTION
      value: "apply"
    - name: AUTO_APPROVE
      value: "true"
    - name: SUB_DIRECTORY
      value: "terraform"
    - name: TF_VARS
      value:
        - "region+-'eu-central-1'"
        - "instance_count+-2"
    - name: BACKEND_CONFIG
      value:
        - "bucket+-my-tf-state"
        - "key+-stage-time/terraform.tfstate"
  workspaces:
    - name: source
      persistentVolumeClaim:
        claimName: terraform-source-pvc
    # optional - private CA trust, per run (omit if not needed)
    - name: ca-certs
      secret:
        secretName: private-ca # pragma: allowlist secret
