---
apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: build-image-buildah
spec:
  params:
    - name: git-url
      type: string
      description: Git repository URL
    - name: branch-name
      type: string
      description: The git branch to clone.
    - name: subdirectory
      type: string
      default: ""
      description: Subdirectory to checkout
    - name: delete-existing
      type: string
      default: "true"
      description: Delete existing content
    - name: context
      type: string
      default: .
      description: The build context (directory).
    - name: dockerfile
      type: string
      default: ./Dockerfile
      description: The path to the Dockerfile.
    - name: storage-driver
      type: string
      default: overlay
      description: The storage driver to use.
    - name: image-name
      type: string
      description: Image name for Buildah to build and push
    - name: verify-ssl
      type: string
      default: "false"
      description: Verify ssl
  workspaces:
    - name: shared-data
      description: |
        This workspace will receive the cloned git repo and be passed
        to the next Task for the repo's README.md file to be read.
    - name: basic-auth
      optional: true
    - name: sslcertdir
      optional: true
    - name: dockerconfig
      optional: true
    - name: registries-conf
      optional: true
  tasks:
    - name: fetch-repository
      taskRef:
        resolver: git
        params:
          - name: url
            value: https://github.com/tektoncd/catalog.git
          - name: revision
            value: main
          - name: pathInRepo
            value: task/git-clone/0.10/git-clone.yaml
      workspaces:
        - name: output
          workspace: shared-data
        - name: basic-auth
          workspace: basic-auth
      params:
      - name: url
        value: $(params.git-url)
      - name: revision
        value: $(params.branch-name)
      - name: sslVerify
        value: $(params.verify-ssl)
      - name: subdirectory
        value: $(params.subdirectory)
      - name: deleteExisting
        value: $(params.delete-existing)
    - name: buildah
      taskRef:
        resolver: git
        params:
          - name: url
            value: https://github.com/stuttgart-things/stage-time.git
          - name: revision
            value: main
          - name: pathInRepo
            value: tasks/build-buildah.yaml
      runAfter:
        - fetch-repository
      workspaces:
        - name: source
          workspace: shared-data
        - name: dockerconfig
          workspace: dockerconfig
        - name: registries-conf
          workspace: registries-conf
      params:
        - name: IMAGE
          value: "$(params.image-name)"
        - name: TLSVERIFY
          value: $(params.verify-ssl)
        - name: CONTEXT
          value: $(params.context)
        - name: DOCKERFILE
          value: $(params.dockerfile)
        - name: STORAGE_DRIVER
          value: $(params.storage-driver)
