---
kind: Secret
apiVersion: v1
metadata:
  name: basic-{{ .scm }}-auth
type: Opaque
stringData:
  .gitconfig: |
    [url "https://{{ .user }}:{{ .token }}@{{ .gitServer }}/{{ .repo }}/"]
        insteadOf = https://{{ .gitServer }}/{{ .repo }}/
    [user]
        name = {{ .name }}
        email = {{ .email }}
  .git-credentials: |
    https://{{ .user }}:{{ .token }}@{{ .gitServer }}/{{ .repo }}
